/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type Algorithm string

// List of Algorithm
const (
	RSA_Algorithm      Algorithm = "RSA"
	RSA15_Algorithm    Algorithm = "RSA15"
	DSA_Algorithm      Algorithm = "DSA"
	EL_GAMAL_Algorithm Algorithm = "ElGamal"
	EC_DSA_Algorithm   Algorithm = "EcDSA"
	ED_DSA_Algorithm   Algorithm = "EdDSA"
	UNKNOWN_Algorithm  Algorithm = "Unknown"
	INVALID_Algorithm  Algorithm = "Invalid"
)
