/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type SoftwareVersions struct {
	CoreLibs  string `json:"coreLibs,omitempty"`
	Main      string `json:"main,omitempty"`
	Peer2peer string `json:"peer2peer,omitempty"`
	Tags      string `json:"tags,omitempty"`
}
