/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type RecordType string

// List of RecordType
const (
	ROOT_RecordType              RecordType = "Root"
	DATA_RecordType              RecordType = "Data"
	CLOSING_RecordType           RecordType = "Closing"
	EMERGENCY_CLOSING_RecordType RecordType = "EmergencyClosing"
	CORRUPTED_RecordType         RecordType = "Corrupted"
)
