/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

import (
	"time"
)

// Chain Id
type ChainIdModel struct {
	// Unique record id
	Id string `json:"id"`
	// Is this record not able to accept new records?
	IsClosedForNewTransactions bool `json:"isClosedForNewTransactions,omitempty"`
	// Last record (serial number)
	LastRecord int64 `json:"lastRecord,omitempty"`
	// Date last record was added
	LastUpdate time.Time `json:"lastUpdate,omitempty"`
	// Licensing status [optional]
	LicensingStatus string `json:"licensingStatus,omitempty"`
	// Name [Optional]
	Name string `json:"name,omitempty"`
	// Chain size in bytes
	SizeInBytes int64 `json:"sizeInBytes,omitempty"`
}
