/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

import (
	"time"
)

type DocumentsTransactionModel struct {
	CanCommitNow bool `json:"canCommitNow,omitempty"`
	// Chain unique ID
	Chain                    string    `json:"chain,omitempty"`
	Comment                  string    `json:"comment,omitempty"`
	Compression              string    `json:"compression,omitempty"`
	CountOfUploadedDocuments int32     `json:"countOfUploadedDocuments,omitempty"`
	DocumentNames            []string  `json:"documentNames,omitempty"`
	Encryption               string    `json:"encryption,omitempty"`
	GeneratePublicDirectory  bool      `json:"generatePublicDirectory,omitempty"`
	Previous                 string    `json:"previous,omitempty"`
	TimeOutLimit             time.Time `json:"timeOutLimit,omitempty"`
	TransactionId            string    `json:"transactionId,omitempty"`
}
