/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type DataField struct {
	Cast               *CastType         `json:"cast,omitempty"`
	Description        string            `json:"description,omitempty"`
	ElementTagId       int64             `json:"elementTagId,omitempty"`
	Enumeration        *EnumerationItems `json:"enumeration,omitempty"`
	EnumerationAsFlags bool              `json:"enumerationAsFlags,omitempty"`
	IsDeprecated       bool              `json:"isDeprecated,omitempty"`
	IsOpaque           bool              `json:"isOpaque,omitempty"`
	Name               string            `json:"name,omitempty"`
	SubDataFields      []DataField       `json:"subDataFields,omitempty"`
	TagId              int64             `json:"tagId,omitempty"`
	Version            int32             `json:"version,omitempty"`
}
