/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

// Chain creation parameters
type ChainCreationModel struct {
	// List of additional apps (only the numeric ids)
	AdditionalApps []int64 `json:"additionalApps,omitempty"`
	// API certificates to authorize with corresponding permissions
	ApiCertificates []CertificatePermitModel `json:"apiCertificates,omitempty"`
	// Description (perhaps intended primary usage) [Optional]
	Description string `json:"description,omitempty"`
	// Emergency closing key password
	EmergencyClosingKeyPassword string       `json:"emergencyClosingKeyPassword"`
	EmergencyClosingKeyStrength *KeyStrength `json:"emergencyClosingKeyStrength,omitempty"`
	KeysAlgorithm               *Algorithm   `json:"keysAlgorithm,omitempty"`
	// App/Key management key password
	ManagementKeyPassword string       `json:"managementKeyPassword"`
	ManagementKeyStrength *KeyStrength `json:"managementKeyStrength,omitempty"`
	// Name
	Name                 string       `json:"name"`
	OperatingKeyStrength *KeyStrength `json:"operatingKeyStrength,omitempty"`
	// Parent record Id [Optional]
	Parent string `json:"parent,omitempty"`
}
