/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type HashAlgorithm string

// List of HashAlgorithm
const (
	SHA1_HashAlgorithm     HashAlgorithm = "SHA1"
	SHA256_HashAlgorithm   HashAlgorithm = "SHA256"
	SHA512_HashAlgorithm   HashAlgorithm = "SHA512"
	SHA3_256_HashAlgorithm HashAlgorithm = "SHA3_256"
	SHA3_512_HashAlgorithm HashAlgorithm = "SHA3_512"
	SHA384_HashAlgorithm   HashAlgorithm = "SHA384"
	COPY_HashAlgorithm     HashAlgorithm = "Copy"
)
