/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type KeyPurpose string

// List of KeyPurpose
const (
	INVALID_KEY_KeyPurpose     KeyPurpose = "InvalidKey"
	KEY_MANAGEMENT_KeyPurpose  KeyPurpose = "KeyManagement"
	ACTION_KeyPurpose          KeyPurpose = "Action"
	CLAIM_SIGNER_KeyPurpose    KeyPurpose = "ClaimSigner"
	ENCRYPTION_KeyPurpose      KeyPurpose = "Encryption"
	PROTOCOL_KeyPurpose        KeyPurpose = "Protocol"
	CHAIN_OPERATION_KeyPurpose KeyPurpose = "ChainOperation"
	FORCE_INTERLOCK_KeyPurpose KeyPurpose = "ForceInterlock"
)
