/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

// Force interlock command details
type ForceInterlockModel struct {
	HashAlgorithm *HashAlgorithm `json:"hashAlgorithm,omitempty"`
	// Required minimum of the serial of the last record in target chain whose hash will be pulled. Default: 0
	MinSerial int64 `json:"minSerial,omitempty"`
	// Id of chain to be interlocked
	TargetChain string `json:"targetChain,omitempty"`
}
