/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type DocumentUploadConfiguration struct {
	DefaultCompression    string   `json:"defaultCompression,omitempty"`
	DefaultEncryption     string   `json:"defaultEncryption,omitempty"`
	FileSizeLimit         int64    `json:"fileSizeLimit,omitempty"`
	Iterations            int32    `json:"iterations,omitempty"`
	PermittedContentTypes []string `json:"permittedContentTypes,omitempty"`
	TimeOutInMinutes      int32    `json:"timeOutInMinutes,omitempty"`
}
