/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type NetworkSeed struct {
	Address               string     `json:"address,omitempty"`
	Id                    *NetworkId `json:"id,omitempty"`
	IsEmpty               bool       `json:"isEmpty,omitempty"`
	IsInvalid             bool       `json:"isInvalid,omitempty"`
	PortNumber            int32      `json:"portNumber,omitempty"`
	TextualRepresentation string     `json:"textualRepresentation,omitempty"`
}
