/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

// Key to permit
type KeyPermitModel struct {
	// Key name, ignored on CertificatePermitModel
	Name string `json:"name,omitempty"`
	// App actions to be permitted by number
	Permissions []string `json:"permissions"`
	// Key valid purposes
	Purposes []KeyPurpose `json:"purposes"`
	// Unique key id
	Id string `json:"id"`
	// Key public key
	PublicKey string `json:"publicKey"`
}
