/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

// List of valid apps in the network
type AppsModel struct {
	// Network name
	Network string `json:"network,omitempty"`
	// Currently valid apps for this network
	ValidApps []IInterlockAppTraits `json:"validApps,omitempty"`
}
