/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type LimitedRange struct {
	Count                 int32  `json:"count,omitempty"`
	IsEmpty               bool   `json:"isEmpty,omitempty"`
	IsInvalid             bool   `json:"isInvalid,omitempty"`
	TextualRepresentation string `json:"textualRepresentation,omitempty"`
}
