/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

import (
	"time"
)

type IInterlockAppTraits struct {
	// A version in the format 'major.minor(.release)'
	AppVersion  string      `json:"appVersion,omitempty"`
	DataModels  []DataModel `json:"dataModels,omitempty"`
	Description string      `json:"description,omitempty"`
	Id          int64       `json:"id,omitempty"`
	Name        string      `json:"name,omitempty"`
	// Key unique ID
	PublisherId        string         `json:"publisherId,omitempty"`
	PublisherName      string         `json:"publisherName,omitempty"`
	ReservedILTagIds   []LimitedRange `json:"reservedILTagIds,omitempty"`
	SimplifiedHashCode int32          `json:"simplifiedHashCode,omitempty"`
	Start              time.Time      `json:"start,omitempty"`
	Version            int32          `json:"version,omitempty"`
}
