/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type NewRecordType string

// List of NewRecordType
const (
	DATA_NewRecordType              NewRecordType = "Data"
	CLOSING_NewRecordType           NewRecordType = "Closing"
	EMERGENCY_CLOSING_NewRecordType NewRecordType = "EmergencyClosing"
)
