/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type KeyStrength string

// List of KeyStrength
const (
	NORMAL_KeyStrength       KeyStrength = "Normal"
	STRONG_KeyStrength       KeyStrength = "Strong"
	EXTRA_STRONG_KeyStrength KeyStrength = "ExtraStrong"
	MEGA_STRONG_KeyStrength  KeyStrength = "MegaStrong"
	SUPER_STRONG_KeyStrength KeyStrength = "SuperStrong"
	HYPER_STRONG_KeyStrength KeyStrength = "HyperStrong"
	ULTRA_STRONG_KeyStrength KeyStrength = "UltraStrong"
)
