/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type DocumentsBeginTransactionModel struct {
	// Chain unique ID
	Chain                   string `json:"chain,omitempty"`
	Comment                 string `json:"comment,omitempty"`
	Compression             string `json:"compression,omitempty"`
	Encryption              string `json:"encryption,omitempty"`
	GeneratePublicDirectory bool   `json:"generatePublicDirectory,omitempty"`
	Iterations              int32  `json:"iterations,omitempty"`
	Password                string `json:"password,omitempty"`
	// A Documents Storage Locator
	Previous string `json:"previous,omitempty"`
}
