/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

import (
	"time"
)

// Generic opaque record
type RecordModel struct {
	ApplicationId int64 `json:"applicationId,omitempty"`
	// Chain unique ID
	ChainId      string     `json:"chainId,omitempty"`
	CreatedAt    time.Time  `json:"createdAt,omitempty"`
	Hash         string     `json:"hash,omitempty"`
	Network      *NetworkId `json:"network,omitempty"`
	PayloadTagId int64      `json:"payloadTagId,omitempty"`
	// A universal record reference in the form networkName:chainId@recordSerial
	Reference string      `json:"reference,omitempty"`
	Serial    int64       `json:"serial,omitempty"`
	Type_     *RecordType `json:"type,omitempty"`
	Version   int32       `json:"version,omitempty"`
	// The payload's bytes
	PayloadBytes string `json:"payloadBytes,omitempty"`
}
