/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

// Generic opaque new record
type NewRecordModel struct {
	// Application id this record is associated with
	ApplicationId int64 `json:"applicationId"`
	// The payload's bytes
	PayloadBytes string      `json:"payloadBytes,omitempty"`
	Type_        *RecordType `json:"type,omitempty"`
}
