/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type NetworkId struct {
	AsBytes        string `json:"asBytes,omitempty"`
	AsHex          string `json:"asHex,omitempty"`
	AsULong        int64  `json:"asULong,omitempty"`
	Checksum       int32  `json:"checksum,omitempty"`
	DefaultAddress string `json:"defaultAddress,omitempty"`
	DefaultPort    int32  `json:"defaultPort,omitempty"`
	// Chain unique ID
	Genesis     string `json:"genesis,omitempty"`
	Inactive    bool   `json:"inactive,omitempty"`
	IsCustom    bool   `json:"isCustom,omitempty"`
	IsEmpty     bool   `json:"isEmpty,omitempty"`
	IsError     bool   `json:"isError,omitempty"`
	IsInvalid   bool   `json:"isInvalid,omitempty"`
	IsLocalOnly bool   `json:"isLocalOnly,omitempty"`
	// Chain unique ID
	LicenseSigners        string         `json:"licenseSigners,omitempty"`
	Name                  string         `json:"name,omitempty"`
	ProxySeeder           *NetworkSeed   `json:"proxySeeder,omitempty"`
	Seeders               []NetworkSeed  `json:"seeders,omitempty"`
	TextualRepresentation string         `json:"textualRepresentation,omitempty"`
	Type_                 *NetworkIdType `json:"type,omitempty"`
}
