/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type CastType string

// List of CastType
const (
	NONE_CastType      CastType = "None"
	DATE_TIME_CastType CastType = "DateTime"
	INTEGER_CastType   CastType = "Integer"
	TIME_SPAN_CastType CastType = "TimeSpan"
)
