/*
 * InterlockLedger Node REST API
 *
 * A node instance inside the peer-to-peer network of the InterlockLedger
 *
 * API version: v7.2.0
 * Contact: core@interlockledger.network
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type InterlockingRecordModelPageOf struct {
	Items              []InterlockingRecordModel `json:"items,omitempty"`
	Page               int32                     `json:"page,omitempty"`
	PageSize           int32                     `json:"pageSize,omitempty"`
	TotalNumberOfPages int32                     `json:"totalNumberOfPages,omitempty"`
	LastToFirst        bool                      `json:"lastToFirst,omitempty"`
}
